name: GitHub metrics
on:
  schedule:
    - cron: "0 */6 * * *"
  # push:
  #   branches: "master"
jobs:

  github-metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Music plugin (Spotify)
        uses: lowlighter/metrics@master
        with:
          filename: charts/metrics.plugin.music.spotify.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes 
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/7cX2qCyWiZdOnmh1rj7Jef
          plugin_music_limit: 5
          plugins_errors_fatal: no
          config_timezone: Europe/Moscow
          use_prebuilt_image: master

      - name: Music plugin (Recent)
        uses: lowlighter/metrics@master
        with:
          filename: charts/metrics.plugin.music.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes 
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_limit: 5
          plugins_errors_fatal: no
          config_timezone: Europe/Moscow
          use_prebuilt_image: master

      # Display coding habits and recent activity (only charts section)
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin (charts)
        uses: lowlighter/metrics@master
        with:
          filename: charts/metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: no
          config_timezone: Europe/Moscow
          use_prebuilt_image: master

      # Display most used languages
      # You can ignore some languages and skip some repositories if you want
      - name: Languages plugin
        uses: lowlighter/metrics@master
        with:
          filename: charts/metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugins_errors_fatal: no
          config_timezone: Europe/Moscow
          use_prebuilt_image: master

      # Display ratio of open/closed/merged issues and pull requests 
      - name: Follow-up plugin
        uses: lowlighter/metrics@master
        with:
          filename: charts/metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: no
          config_timezone: Europe/Moscow
          use_prebuilt_image: master

      # Display number of line changed
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      - name: Lines plugin2
        uses: lowlighter/metrics@master
        with:
          filename: charts/metrics.plugin.lines2.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: no
          config_timezone: Europe/Moscow
          use_prebuilt_image: master

      # Display number of line changed
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      - name: Lines plugin
        uses: lowlighter/metrics@master
        with:
          filename: charts/metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community
          plugins_errors_fatal: no
          config_timezone: Europe/Moscow
          use_prebuilt_image: master

      # Display gists metrics
      - name: Gists plugin
        uses: lowlighter/metrics@master
        with:
          filename: charts/metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: no
          config_timezone: Europe/Moscow
          use_prebuilt_image: master